name: DEPLOY in Web Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy no EC2
        run: |
          echo "${{secrets.KEY_EC2}}" > private_key && chmod 400 private_key
             ssh -o StrictHostKeyChecking=no -i "private_key" ec2-100-29-2-212.compute-1.amazonaws.com "
                 cd /var/www/html/webserver &&
                 sudo git pull "
